// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATqN-0Dezii2bQz15MD0QuyfcUXlMBfSs',
    appId: '1:928219959860:web:06936ed8421e887baab061',
    messagingSenderId: '928219959860',
    projectId: 'dismov',
    authDomain: 'dismov.firebaseapp.com',
    storageBucket: 'dismov.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfBH2U67fxV_S52Fnh-aHRsJbkC-sAP3E',
    appId: '1:928219959860:android:e562004bd2bb925baab061',
    messagingSenderId: '928219959860',
    projectId: 'dismov',
    storageBucket: 'dismov.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8GtyF-_E0_Mboef6xwlD7L58nzzMNc_s',
    appId: '1:928219959860:ios:f6cf37d990edcc98aab061',
    messagingSenderId: '928219959860',
    projectId: 'dismov',
    storageBucket: 'dismov.appspot.com',
    iosBundleId: 'com.example.moviles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8GtyF-_E0_Mboef6xwlD7L58nzzMNc_s',
    appId: '1:928219959860:ios:02d30ab40b261ac3aab061',
    messagingSenderId: '928219959860',
    projectId: 'dismov',
    storageBucket: 'dismov.appspot.com',
    iosBundleId: 'com.example.moviles.RunnerTests',
  );
}
